-- AlterTable
ALTER TABLE "categorias" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "lojas" ADD COLUMN     "temaID" TEXT NOT NULL DEFAULT '#a82424';

-- AlterTable
ALTER TABLE "regioes" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "temas" (
    "id" TEXT NOT NULL,
    "cores" TEXT[],

    CONSTRAINT "temas_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "lojas" ADD CONSTRAINT "lojas_temaID_fkey" FOREIGN KEY ("temaID") REFERENCES "temas"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
